export const BIOMES = {
  cerrado: {
    key: 'cerrado',
    name: 'Cerrado',
    section: 'todos',
    label: 'Lista de Tarefas',
    icon: '🔥',
    animal: '🐺',
    animalName: 'Lobo-guará',
    colors: {
      bg: 'bg-cerrado-50',
      bgMedium: 'bg-cerrado-100',
      text: 'text-cerrado-700',
      textLight: 'text-cerrado-500',
      border: 'border-cerrado-300',
      accent: 'bg-cerrado-500',
      accentHover: 'hover:bg-cerrado-600',
      gradient: 'from-cerrado-400 to-cerrado-600',
      ring: 'ring-cerrado-300',
    },
    hex: { light: '#fef9e7', medium: '#fbe08a', main: '#d4a017', dark: '#926c09' },
  },
  amazonia: {
    key: 'amazonia',
    name: 'Amazônia',
    section: 'pesquisa',
    label: 'Pesquisa & Academia',
    icon: '🌿',
    animal: '🦫',
    animalName: 'Capivara',
    colors: {
      bg: 'bg-amazonia-50',
      bgMedium: 'bg-amazonia-100',
      text: 'text-amazonia-700',
      textLight: 'text-amazonia-500',
      border: 'border-amazonia-300',
      accent: 'bg-amazonia-500',
      accentHover: 'hover:bg-amazonia-600',
      gradient: 'from-amazonia-400 to-amazonia-700',
      ring: 'ring-amazonia-300',
    },
    hex: { light: '#e8f5e9', medium: '#a5d6a7', main: '#2e7d32', dark: '#1b5e20' },
  },
  atlantica: {
    key: 'atlantica',
    name: 'Mata Atlântica',
    section: 'dev',
    label: 'Projetos Dev',
    icon: '💻',
    animal: '🐒',
    animalName: 'Mico-leão-dourado',
    colors: {
      bg: 'bg-atlantica-50',
      bgMedium: 'bg-atlantica-100',
      text: 'text-atlantica-700',
      textLight: 'text-atlantica-500',
      border: 'border-atlantica-300',
      accent: 'bg-atlantica-500',
      accentHover: 'hover:bg-atlantica-600',
      gradient: 'from-atlantica-400 to-atlantica-700',
      ring: 'ring-atlantica-300',
    },
    hex: { light: '#e0f2f1', medium: '#80cbc4', main: '#00796b', dark: '#004d40' },
  },
  caatinga: {
    key: 'caatinga',
    name: 'Caatinga',
    section: 'notas',
    label: 'Notas Livres',
    icon: '🌵',
    animal: '🦎',
    animalName: 'Tatu-bola',
    colors: {
      bg: 'bg-caatinga-50',
      bgMedium: 'bg-caatinga-100',
      text: 'text-caatinga-700',
      textLight: 'text-caatinga-500',
      border: 'border-caatinga-300',
      accent: 'bg-caatinga-500',
      accentHover: 'hover:bg-caatinga-600',
      gradient: 'from-caatinga-400 to-caatinga-600',
      ring: 'ring-caatinga-300',
    },
    hex: { light: '#fdf5e6', medium: '#f5d5a0', main: '#c2956b', dark: '#8b6914' },
  },
  pantanal: {
    key: 'pantanal',
    name: 'Pantanal',
    section: 'conquistas',
    label: 'Conquistas do Dia',
    icon: '🏆',
    animal: '🦩',
    animalName: 'Tuiuiú',
    colors: {
      bg: 'bg-pantanal-50',
      bgMedium: 'bg-pantanal-100',
      text: 'text-pantanal-700',
      textLight: 'text-pantanal-500',
      border: 'border-pantanal-300',
      accent: 'bg-pantanal-500',
      accentHover: 'hover:bg-pantanal-600',
      gradient: 'from-pantanal-400 to-pantanal-600',
      ring: 'ring-pantanal-300',
    },
    hex: { light: '#e3f2fd', medium: '#90caf9', main: '#1565c0', dark: '#0d47a1' },
  },
  pampa: {
    key: 'pampa',
    name: 'Pampa',
    section: 'stats',
    label: 'Estatísticas',
    icon: '📊',
    animal: '🐦',
    animalName: 'Quero-quero',
    colors: {
      bg: 'bg-pampa-50',
      bgMedium: 'bg-pampa-100',
      text: 'text-pampa-700',
      textLight: 'text-pampa-500',
      border: 'border-pampa-300',
      accent: 'bg-pampa-500',
      accentHover: 'hover:bg-pampa-600',
      gradient: 'from-pampa-400 to-pampa-700',
      ring: 'ring-pampa-300',
    },
    hex: { light: '#f1f8e9', medium: '#c5e1a5', main: '#689f38', dark: '#33691e' },
  },
}

export function getBiomeForSection(section) {
  return Object.values(BIOMES).find(b => b.section === section) || BIOMES.cerrado
}

export function getAllBiomeGradient() {
  return 'bg-gradient-to-r from-cerrado-500 via-amazonia-500 via-atlantica-500 via-pantanal-500 to-pampa-500'
}
